# Generated by Django 5.2.5 on 2025-09-09 14:47

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_ratings_count_product_ratings_sum'),
        ('favorites', '0001_initial'),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name='favoriteitem',
            index=models.Index(fields=['product', 'position', '-created_at'], name='idx_fi_prod_pos_cr'),
        ),
    ]
