# Generated by Django 5.2.5 on 2025-09-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favoriteitem_idx_fi_prod_pos_cr'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='favoriteitem',
            name='idx_fi_prod_pos_cr',
        ),
    ]
