# Generated by Django 5.2.5 on 2025-09-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0017_genderfilteroptionsmv_pricerangesmv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products in this cart via CartItem', related_name='carts', through='cart.CartItem', to='catalog.product'),
        ),
    ]
