# Generated by Django 5.2.5 on 2025-08-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rating_idx_rating_prod_score'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='idx_rating_prod_score',
        ),
    ]
