# Generated by Django 5.2.5 on 2025-08-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_rating_idx_rating_prod_score'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='ratings_rat_product_cd5eac_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='ratings_rat_user_id_161600_idx',
        ),
    ]
