# Generated by Django 5.2.5 on 2025-08-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_remove_rating_ratings_rat_product_cd5eac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dislike',
            name='ratings_dis_product_5cd766_idx',
        ),
        migrations.RemoveIndex(
            model_name='dislike',
            name='ratings_dis_user_id_a1a8fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='ratings_lik_product_ff209f_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='ratings_lik_user_id_7c97fc_idx',
        ),
    ]
