# Generated by Django 5.2.5 on 2025-08-21 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_product_idx_article_year_upd_cre_id'),
        ('ratings', '0005_remove_dislike_ratings_dis_product_5cd766_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['product', 'score'], name='idx_rating_product_score'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['product'], name='idx_rating_product'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['product', '-score'], name='idx_rating_product_score_desc'),
        ),
    ]
