# Generated by Django 5.2.5 on 2025-09-09 14:23

from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0016_product_ratings_count_product_ratings_sum'),
        ('ratings', '0006_rating_idx_rating_product_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name='dislike',
            index=models.Index(fields=['product'], name='idx_dislike_product'),
        ),
        AddIndexConcurrently(
            model_name='dislike',
            index=models.Index(fields=['product', 'user'], name='idx_dislike_prod_user'),
        ),
        AddIndexConcurrently(
            model_name='dislike',
            index=models.Index(fields=['product', '-created_at'], name='idx_dislike_prod_created'),
        ),
        AddIndexConcurrently(
            model_name='like',
            index=models.Index(fields=['product'], name='idx_like_product'),
        ),
        AddIndexConcurrently(
            model_name='like',
            index=models.Index(fields=['product', 'user'], name='idx_like_prod_user'),
        ),
        AddIndexConcurrently(
            model_name='like',
            index=models.Index(fields=['product', '-created_at'], name='idx_like_prod_created'),
        ),
    ]
