# Generated by Django 5.2.5 on 2025-09-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_dislike_idx_dislike_product_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='like',
            new_name='idx_like_product_user',
            old_name='idx_like_prod_user',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='idx_like_product_created_desc',
            old_name='idx_like_prod_created',
        ),
    ]
