# Generated by Django 5.2.5 on 2025-10-14 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted', models.CharField(max_length=512)),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=192)),
                ('house', models.CharField(max_length=32)),
                ('apartment', models.CharField(blank=True, max_length=32)),
                ('place_id', models.CharField(max_length=128, unique=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('label', models.CharField(default='Home address', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(related_name='addresses', through='shipping.UserAddress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default'], name='shipping_us_user_id_6cc99a_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_validated'], name='shipping_us_user_id_e2f7ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='uniq_user_default_address'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='uniq_user_label'),
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'address')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['place_id'], name='shipping_ad_place_i_8cd89a_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country', 'city'], name='shipping_ad_country_d7a638_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'street'], name='shipping_ad_city_9b6b94_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('country', 'region', 'city', 'postal_code', 'street', 'house', 'apartment'), name='uniq_address_components'),
        ),
    ]
