# Generated by Django 5.2.5 on 2025-08-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_disliked_by_alter_product_liked_by_and_more'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['is_active', 'stock_quantity', 'reserved_quantity'], name='idx_inventory_availability'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['sale_price'], name='idx_inventory_sale_price'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['is_active', 'sale_price'], name='idx_inventory_discount_filter'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['is_active', 'stock_quantity', 'reserved_quantity', 'sale_price'], name='idx_inventory_complete_filter'),
        ),
    ]
