# Generated by Django 5.2.5 on 2025-08-08 21:00

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='basecolour',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalog.articletype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalog.basecolour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_display_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalog.season'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalog.usagetype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
