# Generated by Django 5.2.5 on 2025-08-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-year', '-updated_at', '-created_at']},
        ),
    ]
