# Generated by Django 5.2.5 on 2025-08-19 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_products', through='ratings.Dislike', through_fields=('product', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_products', through='ratings.Like', through_fields=('product', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='rated_products', through='ratings.Rating', through_fields=('product', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
