# Generated by Django 5.2.5 on 2025-08-20 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_disliked_by_product_liked_by_and_more'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-year', '-updated_at', '-created_at', '-id'], name='idx_year_upd_cre_id_desc'),
        ),
    ]
