# Generated by Django 5.2.5 on 2025-08-20 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_idx_year_upd_cre_id_desc'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_display_name', 'id'], name='idx_name_id_asc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-product_display_name', '-id'], name='idx_name_id_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['year', 'id'], name='idx_year_id_asc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-year', '-id'], name='idx_year_id_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at', 'id'], name='idx_created_id_asc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', '-id'], name='idx_created_id_desc'),
        ),
    ]
