# Generated by Django 5.2.5 on 2025-08-20 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_idx_name_id_asc_product_idx_name_id_desc_and_more'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['article_type', '-year', '-updated_at', '-created_at', '-id'], name='idx_atype_year_upd_cre_desc'),
        ),
    ]
