# Generated by Django 5.2.5 on 2025-08-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_idx_atype_year_upd_cre_desc'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_atype_year_upd_cre_desc',
        ),
    ]
