# Generated by Django 5.2.5 on 2025-08-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_idx_atype_year_upd_cre_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-year', '-updated_at', '-created_at', '-id']},
        ),
    ]
