# Generated by Django 5.2.5 on 2025-08-20 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options'),
        ('ratings', '0002_rating_idx_rating_prod_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['article_type', '-year', '-updated_at', '-created_at', '-id'], name='idx_article_year_upd_cre_id'),
        ),
    ]
