# Generated by Django 5.2.5 on 2025-08-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_idx_article_year_upd_cre_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articletype',
            index=models.Index(fields=['slug'], name='idx_article_slug'),
        ),
        migrations.AddIndex(
            model_name='articletype',
            index=models.Index(fields=['sub_category', 'slug'], name='idx_sub_article_slug'),
        ),
        migrations.AddIndex(
            model_name='mastercategory',
            index=models.Index(fields=['slug'], name='idx_master_slug'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['slug'], name='idx_sub_slug'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['master_category', 'slug'], name='idx_master_sub_slug'),
        ),
    ]
