# Generated by Django 5.2.5 on 2025-08-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_articletype_idx_article_slug_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articletype',
            name='idx_article_slug',
        ),
        migrations.RemoveIndex(
            model_name='articletype',
            name='idx_sub_article_slug',
        ),
        migrations.RemoveIndex(
            model_name='mastercategory',
            name='idx_master_slug',
        ),
        migrations.RemoveIndex(
            model_name='subcategory',
            name='idx_sub_slug',
        ),
        migrations.RemoveIndex(
            model_name='subcategory',
            name='idx_master_sub_slug',
        ),
    ]
