# Generated by Django 5.2.5 on 2025-08-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_articletype_idx_article_slug_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_article_year_upd_cre_id',
        ),
    ]
