# Generated by Django 5.2.5 on 2025-08-26 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_product_idx_article_year_upd_cre_id'),
        ('ratings', '0006_rating_idx_rating_product_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='disliked_products', through='ratings.Dislike', through_fields=('product', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='liked_products', through='ratings.Like', through_fields=('product', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='rated_by',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='rated_products', through='ratings.Rating', through_fields=('product', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
