# Generated by Django 5.2.5 on 2025-09-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_disliked_by_alter_product_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ratings_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
