# Generated by Django 5.2.5 on 2025-09-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_ratings_count_product_ratings_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderFilterOptionsMV',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('master_slug', models.CharField(max_length=255, null=True)),
                ('sub_slug', models.CharField(max_length=255, null=True)),
                ('article_slug', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'mv_filter_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceRangesMV',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('master_slug', models.CharField(max_length=255, null=True)),
                ('sub_slug', models.CharField(max_length=255, null=True)),
                ('article_slug', models.CharField(max_length=255, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specificity', models.IntegerField()),
            ],
            options={
                'db_table': 'mv_price_ranges',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
